name: strava_pro
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  strava_client: ^2.1.2
  intl: ^0.18.0 
  sqflite: ^2.2.2
  path: ^1.9.0
  fluttertoast: ^8.2.12
  flutter_map: ^8.1.0  
  flutter_polyline_points: ^2.1.0
  latlong2: ^0.9.0    
  geolocator: ^13.0.2
  path_provider: ^2.1.5
  permission_handler: ^11.4.0
  device_info_plus: ^9.0.3
  xml: ^6.5.0  # 用于解析 GPX 文件
  fl_chart: ^0.70.2 # 用于绘制图表
  great_circle_distance_calculator: ^1.0.3  # 用于计算两点之间的距离
  flutter_svg: ^2.0.17


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/