name: strava_pro
description: "A new Flutter project."
publish_to: "none"
version: 0.4.15+7

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  strava_client: ^2.1.2
  intl: ^0.20.2
  sqflite: ^2.2.2
  path: ^1.9.0
  fluttertoast: ^8.2.12
  flutter_map: ^8.1.0
  flutter_map_tile_caching: ^10.1.0 # 用于缓存地图瓦片
  flutter_polyline_points: ^2.1.0
  latlong2: ^0.9.0
  geolocator: ^13.0.2
  path_provider: ^2.1.5
  permission_handler: ^11.4.0
  device_info_plus: ^9.0.3
  xml: ^6.5.0 # 用于解析 GPX 文件
  fl_chart: ^0.70.2 # 用于绘制图表
  great_circle_distance_calculator: ^1.0.3 # 用于计算两点之间的距离
  flutter_svg: ^2.0.17
  shared_preferences: ^2.5.3
  http: ^1.3.0
  open_file: ^3.5.10
  home_widget: ^0.7.0+1 # 用于创建桌面小组件
  package_info_plus: ^8.3.0 # 获取应用版本信息
  dio: ^5.4.1 # 下载文件
  # install_plugin: ^2.1.0 # 安装APK - 暂时禁用，等待修复命名空间问题
  url_launcher: ^6.2.4 # 打开URL

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  intl_translation: ^0.20.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/stravaz.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/stravaz.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false
